name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Cache Go dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          src/vendor # Add any relevant paths here if your dependencies are located elsewhere
        key: ${{ runner.os }}-go-${{ hashFiles('src/go.sum') }}

    - name: Build
      run: go build -v
      working-directory: ./src

    - name: Test
      run: go test -v
      working-directory: ./src
