# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Cache Go dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          src/vendor # Add any relevant paths here if your dependencies are located elsewhere
        key: ${{ runner.os }}-go-${{ hashFiles('src/go.sum') }}

    - name: Build
      run: go build -v ./...
      working-directory: ./src

    - name: Test
      run: go test -v ./...
      working-directory: ./src
